# Use a lightweight image of nginx as base image
FROM nginx:alpine

# Copy the frontend directory to the default nginx public directory
COPY . /usr/share/nginx/html

# Expose port 80 for incoming traffic
EXPOSE 80
