version: "3.3"

services:
  express:
    build: ./backend
    container_name: express
    restart: always
    ports:
      - "3000:3000"
    
  nginx:
    build: ./frontend
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - express
